### ISSUE TITLE
[FR] Option to turn off the auto-filling for empty `.ahk` files

### ISSUE THREAD

**Issue by wenfangdu** [vscode-autohotkey/ahkpp#105]
Currently, when creating a new `.ahk` file, after closing and reopening the file, AHK++ will auto-fill it with the following lines:

```
#SingleInstance, Force
SendMode Input
SetWorkingDir, %A_ScriptDir%
```

Would be nice to have an option to disable the auto-filling.

**Comment by mark-wiemer** [comment]
See also #93
