### ISSUE TITLE
[FR] Add an option to disable the snippets entirely

### ISSUE THREAD

**Issue by wenfangdu** [vscode-autohotkey/ahkpp#108]

**Comment by mark-wiemer** [comment]
Hi @wenfangdu, can you elaborate on this? There are many settings provided by default to hide suggestions, but I'm not sure exactly what you mean by `snippets`, whether you'd like to hide AHK-specific stuff or all things, etc.

**Comment by wenfangdu** [comment]
@mark-wiemer Hi, just to hide the snippets provided by AHK++, since the snippets are often longer than I actually need.

**Comment by mark-wiemer** [comment]
@wenfangdu Can you send a few examples of snippets you'd like to hide?

**Comment by wenfangdu** [comment]
@mark-wiemer Examples (current => desired):

- `WinActivate, [ WinTitle, WinText, ExcludeTitle, ExcludeText]` => `WinActivate`
- `WinExist("WinTitle" [, "WinText", "ExcludeTitle", "ExcludeText"])` => `WinExist`

Basically, parameters are better omitted.

**Comment by jc9108** [comment]
@wenfangdu i suggest you use the [Control Snippets](https://marketplace.visualstudio.com/items?itemName=svipas.control-snippets) extension, you can disable snippets from other extensions like this::
![image](https://user-images.githubusercontent.com/31039318/194921398-831de6dc-2a19-48e7-9e42-32ae0d729f33.png)

**Comment by mark-wiemer** [comment]
The code for this one is open-source, we'll keep this feature request on the backlog as it should be possible to integrate into the extension itself :)

**Comment by mark-wiemer** [comment]
Since this is already supported by a working extension, I'm closing this one as not planned
