### ISSUE TITLE
Debugger can't connect to a file with a space in its name

### ISSUE THREAD

**Issue by RaptorX** [vscode-autohotkey/ahkpp#134]
Issue Type: <b>Bug</b>

* Create File called "My - Test.ahk"
* Add break point
* Run with F9

## Result
* The breakpoint is ignored

## Expected
* Script should stop at first breakpoint

## Notes
Changing the file name to anything that doesnt contain " - " works perfectly fine: "My test.ahk" would behave as expected.

I narrowed down the bug to the following:
* " -" (space with dash) in file name breaks the debugger
* "- " (dash with space) in file name doesnt break the debugger

Extension version: 2.8.2
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (22.79GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\OneDrive\\Documents\\AutoHotkey\\lib\\v1\\UIAutomation --crash-reporter-id 1eed22db-bc5c-446b-a877-f742be520d0c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by fade2gray** [comment]
I might be wrong, but I think this is more a VS Code thing, that doesn't like the dashes, rather than the fault of AHK++.

If you copy files within VS Code's explorer, you don't get the dashes, but you do when copying files in Window's explorer.

VS Code explorer:
* test.ahk
* test copy.ahk
* test copy 2.ahk

Windows explorer:
* test.ahk
* test - copy.ahk
* test - copy (2).ahk

¯\\_(ツ)_/¯

**Comment by mark-wiemer** [comment]
This is an AHK++ thing :/ JavaScript debugger works just fine here.

![image](https://user-images.githubusercontent.com/7833360/175799593-f491b575-40d8-4e7e-a193-29555d75a550.png)

Note the choice to add a `-` when copying a file is definitely different between Windows Explorer and VS Code, but I don't think that's impacting this issue. VS Code should is able to handle dashes just fine, it just chooses not to create them when copying (for simplicity, I imagine?)

**Comment by mark-wiemer** [comment]
Looks like the issue occurs whenever there is a space in the filename, likely related to the space being used as a separator in standard shells. Basic fixes aren't working yet, but this is next on the list :)
