### ISSUE TITLE
Support AHK v2

### ISSUE THREAD

**Issue by mark-wiemer** [vscode-autohotkey/ahkpp#146]
**Is your feature request related to a problem? Please describe.**
I want to write AHK v2, but all the snippets and suggestions are for v1

**Describe the solution you'd like**
This extension should know whether I'm writing AHK v2 or v1, and give me relevant snippets

**Describe alternatives you've considered**
Currently I'm looking for other extensions or using other IDEs

**Comment by safetycar** [comment]
A really extensive list of changes is here: https://lexikos.github.io/v2/docs/v2-changes.htm

But the most noticeable are the visual issues when you try to use apostrophe (') for string literals. And the change in behavior of `/* */` . Previously the closing needed to be at the beginning of the line. For example in v1 you can't put a title /* like this */ but you could in v2, but currently the styling says that everything after that is a comment.

**Comment by mark-wiemer** [comment]
Dupe of #96
