### ISSUE TITLE
Snippets inconsistencies.

### ISSUE THREAD

**Issue by anonymous1184** [vscode-autohotkey/ahkpp#249]
The v3.0.0 includes #202, and the logic behind the changes is that v2 compatibility is improved.

`#Warn` is missing; it should (***must***?) be enabled. I don't even know why AHK has an option to disable it.

The `#SingleInstance` directive has the same default value in both versions. Why use it on the extension template? The AHK default template doesn't use it.

Wouldn't be more appropriate not to have a template? It is cumbersome to delete it every time a new file is created (to the point I override the snippet with a blank one).

Also, more importantly, the commands have an initial comma. In v2 that's not valid. The same goes for all the directives, commands, and control flow statements.

Here's a `.patch` fixing the last issue and a couple of spelling issues. Perhaps there are more issues, I didn't check the file word by word, I just glanced over it.

[ahk.json.patch.gz](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/files/9725105/ahk.json.patch.gz)

---

EDIT: Uploaded the wrong archive, fixed now.

**Comment by mark-wiemer** [comment]
I've addressed the template issues in a PR that'll auto-merge in a few minutes. Would you mind creating a separate issue for the snippets? v2 support will be difficult and I'm still focusing on low-hanging fruit, but I'm happy to consider any changes you suggest.
