### ISSUE TITLE
Default AHK++ hotkey F9 override default VS Code hotkey F9

### ISSUE THREAD

**Issue by kyklish** [vscode-autohotkey/ahkpp#280]
Default **AHK++** hotkey `F9` (Debug Script) override default **VS Code** hotkey `F9` (Toggle Breakpoint).

Can't set breakpoint with default **VS Code** hotkey.

There are no available `Fx` hotkey to fix this issue :(

**Comment by fade2gray** [comment]
I changed the debug keybinding to `Ctrl+Shift+Alt+F5`.

**Comment by fade2gray** [comment]
@mark-wiemer 

Don't know why I included 'Shift', as there is nothing natively bound to 'Ctrl+Alt+F9' ¯\\_(ツ)_/¯
