### ISSUE TITLE
How to prevent brace indent?

### ISSUE THREAD

**Issue by ahdung** [vscode-autohotkey/ahkpp#282]
Current:
```AutoHotKey
~Enter::
    {
        if WinExist("信息显示窗口")
            WinClose
    }
```
I want:
```AutoHotKey
~Enter::
{
    if WinExist("信息显示窗口")
        WinClose
}
```

**Comment by mark-wiemer** [comment]
That's not a feature yet, but it makes sense that it should be supported. It's on the backlog now :)

**Comment by ahdung** [comment]
Great! And remove extra spaces by the way please: `Foo ( "xx" )` to `Foo("xx")`.

**Comment by mark-wiemer** [comment]
Please open a separate bug so we can track everything individually :)

**Comment by kyklish** [comment]
You can disable code indentation in extension's settings.

**Comment by ahdung** [comment]
@kyklish It's worked, Thank you.
