### ISSUE TITLE
Autohotkey Execute Bin Not Found

### ISSUE THREAD

**Issue by perettigiuliano** [vscode-autohotkey/ahkpp#302]
HI, even if I have this set up:
"ahk++.file.executePath": "C:\\Users\\giuliano.peretti\\AppData\\Local\\Microsoft\\WindowsApps\\AutoHotkeyU64.exe"
![image](https://user-images.githubusercontent.com/148322/209444669-418c4b4a-b551-4d5b-be28-45b1237fb989.png)
when I try to debug I have:
![image](https://user-images.githubusercontent.com/148322/209444695-df670e6b-269a-4ada-a516-31758631e4cd.png)

Any suggestion?

**Comment by kyklish** [comment]
All `exe` files has `0 KB` size on screenshot. Why?

**Comment by fade2gray** [comment]
Is it possible that AutoHotkey has been installed somewhere other than the default location of `C:\Program Files\AutoHotkey`? If so, the path will have to be changed in the settings.

![ahk++](https://user-images.githubusercontent.com/1332009/209448207-616ae8ce-dd7d-4a70-9a44-8f57e3ae1b84.png)

**Comment by perettigiuliano** [comment]
good point, true.
but there is something strange (I mean that I don't understand)...
i.e. if I execute "Ahk2Exe.exe" (has size 0) from that location:
![image](https://user-images.githubusercontent.com/148322/209451805-bed6b20b-902b-4ead-9602-2c91166930c5.png)
If via "Task Manager" I open files location for this new process it opens:
![image](https://user-images.githubusercontent.com/148322/209451827-4b7777a1-af73-4e93-b3df-2e3dfe66ffb9.png)

I have to say that this installation is coming from "Microsoft Store"

**Comment by fade2gray** [comment]
Beyond my knowledge. You may need to wait for @mark-wiemer to get back from Xmas break for his advice.

**Comment by mark-wiemer** [comment]
Hey @perettigiuliano, the files you're showing in the 0 KB screenshots are shortcuts, that's why they're 0 KB. You'll want to change the path to the AutoHotkey.exe to that "poweredbyweatherlights" folder which contains the actual applications.

As a side note, I'm not sure where you got this installation from. The trusted installations always come directly from https://autohotkey.com. If you're not sure where this folder came from, I'd recommend deleting it and re-installing from the trusted site.

Closing this one as a user issue, feel free to open a discussion if you're having more trouble getting the extension configured :)

**Comment by perettigiuliano** [comment]
Hi, the installation is coming from Microsoft Store. Is it not trusted?

**Comment by mark-wiemer** [comment]
It's probably OK :) note I do work for Microsoft so I'm a bit biased, you're welcome to do your research into the publisher who put it on the store.

**Comment by racingcow** [comment]
Installed this today and had a sort of similar issue. Dropping this note here in case it helps anyone else. My problem was that the default install path was `C:/Program Files/AutoHotkey/v2/AutoHotkey64.exe`. Updating the settings as suggested by @fade2gray resolved the my issue. Also note that when I set the path to point to `AutoHotkey64_UIA.exe`, the debugger didn't seem to do anything.

**Comment by mark-wiemer** [comment]
Hey @racingcow, [UIA only works if the script to run is within the Program Files directory](https://www.autohotkey.com/docs/v1/Program.htm#Installer_uiAccess), that's probably why you had the issue. And yes, the defaults may need to be updated with the official v2 release now. Thanks for dropping this note :)
