### ISSUE TITLE
No indent after complex hotkey, hotstring

### ISSUE THREAD

**Issue by kyklish** [vscode-autohotkey/ahkpp#303]
### Expected formatted output snippet

```autohotkey
F1 & F2 Up::
    code
return

::btw::
    code
return
```

### Actual formatted output snippet

```autohotkey
F1 & F2 Up::
code
return

::btw::
code
return
```

**Comment by mark-wiemer** [comment]
@kyklish are you sure the expectation is to indent after the hotstring?

```ahk
::btw::by the way
    code
return
```

PR #304 explicitly adds a [test to keep the code not indented](https://github.com/vscode-autohotkey/ahkpp/pull/304#discussion_r1090072683)

**Comment by CoffeeChaton** [comment]
```ahk
#Warn All

; no problem
::ahk::autohotkey 

; also no problem
::text::
MsgBox, % "text" 
return

; but...
::btw::by the way
MsgBox, % "text" ; open "#Warn, All" -> Warning: This line will never execute, due to Return preceding it.
return

; or can't run of this case
;
; ::btw2::by the way
; by the way2
; return
```

Did I miss something?

**Comment by kyklish** [comment]
> @kyklish are you sure the expectation is to indent after the hotstring?
> 
> ```ahk
> ::btw::by the way
>     code
> return
> ```
> 
> PR #304 explicitly adds a [test to keep the code not indented](https://github.com/vscode-autohotkey/ahkpp/pull/304#discussion_r1090072683)

My typo in bug description. Got fix first message.
