### ISSUE TITLE
AHK++ extentension fails to install in MS Visual Studio 2022

### ISSUE THREAD

**Issue by ZB36Peter** [vscode-autohotkey/ahkpp#353]
I am trying to use the AHK(++) extension in MS Visual Studio 2022 release 17.5.2

Attempt 1: VS > Extension > Manage extensions does not find any AHK editor
Attempt 2: On marketplace.visualstudio.com I find several AHK editors.  
In the case of AHK++ the install button responds but nothing happens.
Attempt 3: download vsix file
Double click the file and get VSIX installer fatal error: one or more extensions are for Visual Studio Code.  Try installing them in Visual Studio Code (Seems like a circular reference)

Any suggestions on what I do wrong and how to get AHK(++) editor to work in VS?

**Comment by fade2gray** [comment]
Quoting README.md, "AutoHotkey Plus Plus (AHK++) provides AutoHotkey language support for **VS Code**."

https://code.visualstudio.com/

**Comment by ZB36Peter** [comment]
Quoting README.md, "AutoHotkey Plus Plus (AHK++) provides AutoHotkey language support for VS Code."

Thanks for the quick response.  As a complete newby to VS(Code) I only now realised that Visual Studio Code is a completely different thing from Visual Studio.  Thanks for (indirectly) pointing that out to me...

**Comment by fade2gray** [comment]
>  Thanks for (indirectly) pointing that out to me...

You're welcome, just highlighting the value of reading 'the back of the box' - we've all been there 😁

**Comment by ZB36Peter** [comment]
I usually do read the back of the box but my misguided interpretation was that the marketplace extensions were code for Visual Studio.  Didn't realize it concerned two different products altogether. Previously I would execute AHK Studio code to open an AHK script editor.  That got me on a similar line of thinking of Code for Visual Studio.  I have now installed the VS Code with the AHK Plus Plus extension and it looks great.  Thanks again...
