### ISSUE TITLE
Comment highlighted differently depending on indentation

### ISSUE THREAD

**Issue by RussF1** [vscode-autohotkey/ahkpp#357]
## Code snippet
```
; Test::Comment
    ; Test::Comment
```

## Expected behavior

Both comments should be highlighted identically

## Editor tokens and scopes

![image](https://github.com/vscode-autohotkey/ahkpp/assets/134521769/420fbc1b-8ecd-4122-81f3-ef7345747a46)

## Additional context

Seems to only happen when there is a double colon between words and the comment is indented via tab or spaces.

![image](https://github.com/vscode-autohotkey/ahkpp/assets/134521769/1e08a350-991b-4dda-be05-1009504ca842)

**Comment by kyklish** [comment]
Very strange. Comment detection has the highest priority. Example text is captured by this regex `(?<=^|\s+)(;).*`, but somehow it is not captured in VSCode grammar parser.

**Comment by kyklish** [comment]
> Very strange. Comment detection has the highest priority. Example text is captured by this regex `(?<=^|\s+)(;).*`, but somehow it is not captured in VSCode's grammar parser and jumps to hotkey detection.

Now I got it. Fix on the way...
