### ISSUE TITLE
Syntax highlighting for conditional directives

### ISSUE THREAD

**Issue by mark-wiemer** [vscode-autohotkey/ahkpp#69]
## Additional context

From @zaregg in #66

For the code snippet
```ahk
#If WinActive("ahk_class Notepad”) or WinActive(MyWindowTitle)
#Space::MsgBox You pressed Win+Spacebar in Notepad or %MyWindowTitle%.
```

Currently the syntax highlighting for this #if statement is like this:
![image](https://user-images.githubusercontent.com/7833360/110720479-7bc44c00-81c3-11eb-844a-4a168f3288ac.png)

In the AutoHotkey documentation, however, it's like this:
![image](https://user-images.githubusercontent.com/7833360/110720482-7d8e0f80-81c3-11eb-8622-d56ac6030c14.png)

It would be very nice to see this kind of syntax highlighting also implemented in this extension :D

**Comment by boromyr** [comment]
+1
