### ISSUE TITLE
"Link" not recognized as keyword

### ISSUE THREAD

**Issue by BartmanEH** [vscode-autohotkey/ahkpp#85]
The keyword 'Link', which is an AHK GuiControl, is not recognized as such and is treated as a variable
## Reproduction steps
```
Gui, 1:Add, Edit,, sample text
Gui, 1:Add, Link,, sample <a href="http://[...]">link</a>
Gui, 1:Add, Text,, sample text

```
Results in unexpected syntax coloring:
![image](https://user-images.githubusercontent.com/6135879/116718925-7eb01180-a9a8-11eb-9956-a9ccd3c89eda.png)
## Expected behavior
'Link' keyword color should be same as 'Edit' or 'Text' (not sure which)

**Comment by mark-wiemer** [comment]
@BartmanEH , thanks for the report. This will definitely be covered by #128, but I may be able to hack together something in the short term. The only thing stopping me is tests, which I'm researching now :)

**Comment by mark-wiemer** [comment]
Creating new issues for "Edit" being seen as a function instead of a keyword like other Gui control types
