### ISSUE TITLE
comment after '#Include' not recognized as comment

### ISSUE THREAD

**Issue by BartmanEH** [vscode-autohotkey/ahkpp#86]
## Description
a comment inserted after an Include statement is treated like a string instead of a comment:
![image](https://user-images.githubusercontent.com/6135879/116719140-bb7c0880-a9a8-11eb-935b-6b022ae8d44f.png)
## Expected behavior
The comment after #Include should be syntax colored the same as other comments

**Comment by BartmanEH** [comment]
gosh, almost 2 years ago... I notice this issue still persists in release v3.1.0. Do I just wait for a new release for this fix to be included?

**Comment by kyklish** [comment]
> Do I just wait for a new release for this fix to be included?

Yes, I think there will be more fixes in next release.
